Repository UPEI-Android/group-project-mindjogg, pull requests merged in 2022-01, with the labels that each got.

#12 Dev to stage
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  app/client/readme.md
  app/database/readme.md
  app/database/schema/readme.md
  app/server/readme.md
Labels: Environment - Stage, Status - Pending Peer Review, Urgent

#11 Dev expressjs setup
  app/server/package-lock.json
  app/server/package.json
  app/server/server.js
Labels: Environment - Dev, Status - Pending Peer Review, Urgent

#14 Initialization React Native Project with Expo CLI
  app/client/mindjogg/.expo-shared/assets.json
  app/client/mindjogg/.gitignore
  app/client/mindjogg/App.js
  app/client/mindjogg/app.json
  app/client/mindjogg/babel.config.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/readme.md
Labels: Environment - Dev, Status - Pending Peer Review

#28 Dev pipeline
  .github/workflows/main.yml
  app/client/mindjogg/.eslintrc.json
  app/server/.eslintrc.json
  app/server/server.js
  app/server/server.test.js
Labels: enhancement, Environment - Dev, Status - Pending Peer Review, Urgent

#27 Create basic authentication functions in Server using bcrypt as hashi…
  app/server/package-lock.json
  app/server/package.json
  app/server/request.http
  app/server/server.js
Labels: Environment - Dev, Status - Pending Peer Review, Urgent

#31 The MVC design pattern set up for server
  app/server/account_management/account_management_app.js
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/user_management_model.js
  app/server/account_management/routes/user_management_routes.js
  app/server/package-lock.json
  app/server/package.json
  app/server/server.js
Labels: Environment - Dev, Status - Pending Peer Review, Urgent

#32 configure the server to dynamic port
  app/server/config/server_config.js
  app/server/package.json
  app/server/server.js
Labels: enhancement, Environment - Dev, Status - Pending Peer Review

#33 Dev backend crud login
  app/server/account_management/account_management_app.js
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/schema/readme.md
  app/server/account_management/models/schema/user_schema.js
  app/server/account_management/models/user_management_model.js
  app/server/database/database_connection.js
  app/server/request.http
  app/server/server.js
Labels: Environment - Dev, Status - Pending Peer Review, Urgent

#67 Emergency Services Research Added
  app/client/mindjogg/App.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/yarn.lock
  app/research/support.md
  app/research/support_schema.md
Labels: Status - Completed

#66 Email automation added
  app/server/account_management/account_management_app.js
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/user_management_model.js
  app/server/config/server_config.js
  app/server/database/database_connection.js
  app/server/package-lock.json
  app/server/package.json
  app/server/request.http
Labels: Status - Pending Peer Review

#96 Dev eslint rules
  app/client/mindjogg/.eslintrc.json
  app/client/mindjogg/App.test.js
  app/client/mindjogg/babel.config.js
  app/server/.eslintrc.json
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/schema/user_schema.js
  app/server/account_management/models/user_management_model.js
  app/server/account_management/routes/user_management_routes.js
  app/server/server.test.js
Labels: Status - Pending Peer Review

#97 Forget password and reset email link done
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/schema/user_schema.js
  app/server/account_management/models/user_management_model.js
  app/server/account_management/routes/user_management_routes.js
  app/server/config/server_config.js
  app/server/package-lock.json
  app/server/package.json
  app/server/request.http
Labels: Environment - Dev, Status - Pending Peer Review

#102 Dev client folderstructure
  app/client/mindjogg/App.js
  app/client/mindjogg/assets/favicon.png
  app/client/mindjogg/components/README.txt
  app/client/mindjogg/screens/README.txt
Labels: bug, Environment - Dev, Status - Pending Peer Review, Urgent

#101 added server docker with the new branch
  app/server/.dockerignore
  app/server/Dockerfile
  app/server/readme.md
Labels: documentation, enhancement, Environment - Dev, Status - Pending Peer Review
