Repository UPEI-Android/group-project-mindjogg, pull requests merged in 2022-02, with the labels that each got.

#107 Logo resize
  app/client/mindjogg/assets/Getting started main logo.png
  app/client/mindjogg/assets/favicon.png
Labels: Status - Completed

#105 Add stack Navigator
  app/client/mindjogg/.eslintrc.json
  app/client/mindjogg/App.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/acoount_management/SignInScreen.js
  app/client/mindjogg/screens/acoount_management/SignUpScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportDescriptionScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportListScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportMainScreen.js
  app/client/mindjogg/screens/navigation/AccountManagementStackNavigator.js
  app/client/mindjogg/screens/navigation/EmergencySupportStackNavigator.js
  app/client/mindjogg/screens/navigation/PositiveJournalStackNavigator.js
  app/client/mindjogg/screens/navigation/SmartGoalStackNavigator.js
  app/client/mindjogg/screens/positive_journal/PositiveJournalEditScreen.js
  app/client/mindjogg/screens/positive_journal/PositiveJournalMainScreen.js
  app/client/mindjogg/screens/smart_goals/SmartGoalEditScreen.js
  app/client/mindjogg/screens/smart_goals/SmartGoalMainScreen.js
  app/client/mindjogg/yarn.lock
Labels: enhancement, Environment - Dev, Status - Pending Peer Review, Urgent

#113 Documentation for UX Survey
  app/documentation/ux_testing/ux_phase1.md
Labels: documentation

#114 Meterial Bottom tab navigation
  app/client/mindjogg/App.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/navigation/AccountManagementStackNavigator.js
  app/client/mindjogg/screens/navigation/AccountManagementTabNavigator.js
  app/client/mindjogg/screens/navigation/EmergencySupportStackNavigator.js
  app/client/mindjogg/screens/navigation/EmergencySupportTabNavigator.js
  app/client/mindjogg/screens/navigation/PositiveJournalStackNavigator.js
  app/client/mindjogg/screens/navigation/PositiveJournalTabNavigator.js
  app/client/mindjogg/screens/navigation/SmartGoalStackNavigator.js
  app/client/mindjogg/screens/navigation/SmartGoalTabNavigator.js
  app/client/mindjogg/yarn.lock
Labels: enhancement, Environment - Dev, Status - Pending Peer Review, Urgent

#109 Email templates done
  app/server/account_management/models/schema/user_schema.js
  app/server/account_management/models/user_management_model.js
  app/server/package-lock.json
  app/server/package.json
  app/server/request.http
  app/server/views/resetPassword.handlebars
  app/server/views/verificationEmail.handlebars
Labels: Status - Pending Peer Review

#118 Standard Text Button
  app/client/mindjogg/App.js
  app/client/mindjogg/components/README.txt
  app/client/mindjogg/components/StdButton/StdButton.js
  app/client/mindjogg/components/StdButton/StdButton.md
  app/client/mindjogg/components/Textbox/Textbox.js
  app/client/mindjogg/components/Textbox/Textbox.md
  app/client/mindjogg/components/Textbox/Textbox.test.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/acoount_management/SignInScreen.js
  app/client/mindjogg/screens/positive_journal/PositiveJournalMainScreen.js
  app/client/mindjogg/screens/smart_goals/SmartGoalMainScreen.js
  app/client/mindjogg/yarn.lock
  app/server/.gitignore
  app/server/request.http
Labels: documentation, enhancement, Status - Pending Peer Review, Urgent

#120 added test suite for stack nav
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/acoount_management/SignInScreen.js
  app/client/mindjogg/screens/acoount_management/SignUpScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportDescriptionScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportListScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportMainScreen.js
  app/client/mindjogg/screens/navigation/AccountManagementStackNavigator.js
  app/client/mindjogg/screens/positive_journal/PositiveJournalEditScreen.js
  app/client/mindjogg/screens/positive_journal/PositiveJournalMainScreen.js
  app/client/mindjogg/screens/smart_goals/SmartGoalEditScreen.js
  app/client/mindjogg/screens/smart_goals/SmartGoalMainScreen.js
  app/client/mindjogg/tests/navigation/AccountManagementStackNavigator.test.js
  app/client/mindjogg/tests/navigation/EmergencySupportStackNavigator.test.js
  app/client/mindjogg/tests/navigation/PositiveJournalStackNavigator.test.js
  app/client/mindjogg/tests/navigation/SmartGoalStackNavigator.test.js
  app/client/mindjogg/yarn.lock
Labels: Environment - Dev, Urgent, testing

#148 Dev custom drawer
  app/client/mindjogg/App.js
  app/client/mindjogg/screens/navigation/DrawerContent.js
  app/client/mindjogg/screens/navigation/DrawerNavigator.js
Labels: enhancement, Environment - Dev, Urgent

#153 Emergency Call Feature Documentation
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/yarn.lock
  app/documentation/phonecall_package.md
Labels: documentation

#159 Support Schema Implemented and Documentation Updated
  app/documentation/support_schema.md
  app/server/emergency_support_app/model/support_schema.js
Labels: Environment - Dev, Status - Pending Peer Review

#161 Dev emergency api tests
  app/server/app.js
  app/server/emergency_app/controllers/emergency_controller.js
  app/server/emergency_app/emergency_support_app.js
  app/server/emergency_app/models/emergency_model.js
  app/server/emergency_app/models/schema/support_schema.js
  app/server/emergency_app/routes/emergency_support_routes.js
  app/server/emergency_app/tests/emergency.test.js
  app/server/package-lock.json
  app/server/request.http
Labels: Status - Pending Peer Review
