Repository UPEI-Android/group-project-mindjogg, pull requests merged in 2022-03, with the labels that each got.

#156 Dev card component
  app/client/mindjogg/components/StdCard/StdCard.js
  app/client/mindjogg/components/StdCard/StdCard.md
Labels: Status - Pending Peer Review

#178 Dev Authentication Screen Set up
  app/client/mindjogg/App.js
  app/client/mindjogg/components/conext/authenticationContext.js
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/acoount_management/ForgotPasswordScreen.js
  app/client/mindjogg/screens/acoount_management/SignInScreen.js
  app/client/mindjogg/screens/acoount_management/SignUpScreen.js
  app/client/mindjogg/screens/navigation/AuthenticationStackNavigator.js
  app/client/mindjogg/screens/navigation/DrawerContent.js
  app/client/mindjogg/tests/navigation/AccountManagementStackNavigator.test.js
  app/client/mindjogg/yarn.lock
Labels: enhancement, Environment - Dev, Status - Pending Peer Review, Urgent

#165 Dev editprofile backend
  app/server/account_management/controllers/user_management_controller.js
  app/server/account_management/models/user_management_model.js
  app/server/account_management/routes/user_management_routes.js
  app/server/account_management/tests/editprofile.test.js
  app/server/emergency_app/routes/emergency_support_routes.js
  app/server/request.http
Labels: Status - Pending Peer Review

#169 Dev documentation login done
  app/client/mindjogg/App.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportListScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportMainScreen.js
  app/client/mindjogg/tests/navigation/EmergencySupportStackNavigator.test.js
  app/documentation/editprofile.md
  app/documentation/emergency_support.md
  app/documentation/login.md
Labels: Status - Pending Peer Review

#186 Linking Emergency API with Frontend Screen
  app/client/mindjogg/App.js
  app/client/mindjogg/components/StdCard/StdCard.md
  app/client/mindjogg/package-lock.json
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/emergency_support/EmergencySupportMainScreen.js
  app/client/mindjogg/tests/navigation/EmergencySupportStackNavigator.test.js
  app/client/mindjogg/yarn.lock
  app/server/request.http
Labels: enhancement

#187 Dev moodtracker backend
  app/documentation/moodtracker.md
  app/server/account_management/models/schema/user_schema.js
  app/server/account_management/models/user_management_model.js
  app/server/app.js
  app/server/database/database_connection.js
  app/server/emergency_support_app/model/support_schema.js
  app/server/moodtracker_app/controllers/moodtracker_controller.js
  app/server/moodtracker_app/models/moodtracker_model.js
  app/server/moodtracker_app/moodtracker_app
  app/server/moodtracker_app/routes/moodtracker_routes.js
  app/server/moodtracker_app/routes/verifyToken.js
  app/server/moodtracker_app/tests/moodtracker.test.js
  app/server/request.http
Labels: Status - Pending Peer Review

#191 Dev connect acct backend
  app/client/mindjogg/App.js
  app/client/mindjogg/package.json
  app/client/mindjogg/screens/acoount_management/SignInScreen.js
  app/client/mindjogg/screens/acoount_management/SignUpScreen.js
  app/client/mindjogg/screens/emergency_support/EmergencySupportMainScreen.js
  app/client/mindjogg/tests/navigation/EmergencySupportStackNavigator.test.js
Labels: Status - Pending Peer Review
